language: python
python: 3.5
sudo: false
branches:
  only:
  - master
  - develop
services:
- docker
env:
  global:
  - AWS_ACCESS_KEY_ID='foo' AWS_DEFAULT_REGION='us-east-1' AWS_SECRET_ACCESS_KEY='bar'
    DATABASE_URL=postgresql://briefy:briefy@127.0.0.1:9999/briefy-leica SQS_IP=127.0.0.1
    SQS_PORT=5000 USER_SERVICE_BASE=https://api.stg.briefy.co/internal
  matrix:
  - TOXENV=py35
install:
- docker run -d -p 127.0.0.1:5000:5000 --name sqs briefy/aws-test:latest sqs
- docker run -d -p 127.0.0.1:9999:5432 -e POSTGRES_PASSWORD=briefy -e POSTGRES_USER=briefy
  -e POSTGRES_DB=briefy-leica --name briefy-leica-test mdillon/postgis:9.5
- pip install -r requirements/dev.txt
- pip install flake8
script:
- tox -e ${TOXENV}
- flake8 src/briefy/leica tests setup.py
after_success:
- make docs
notifications:
  slack: briefy:qxjOPwcrGEtVx3aCQBr812t9
deploy:
  provider: deis
  controller: https://deis.stg.briefy.co
  cli_version: v2.2.0
  app: briefy-leica
  username: ci
  password:
    secure: QFFi1datgLUGGIndn8M5Ht5+rgvNxcMP2M+5jK+8awWR3HoAV5i0s0/9ykDWe5/qX7C78BO703qCYrNUYyTIPqbGHcvL8rx2c1mCNUfdToc32ohias3alZn+14LintzodZz6qnxZogJgNPljCD2G5mOjGEXD1rY/mjRu593y4gB48e+KXYuLj8qL8SMjQWgp5K0g1HUlQacJ3CyrAyku8WVSFBGHbgbUx1y+//XA40vWKDDOonusl6SVPms2+Z/E2NvvBPuIbgPLEArygTLCJ7CGnQQvUA335+g3Uhc9YEDV4curfUgDKcW3d63nTsv0L4dKlVmMy5sB+06XKvoAaoF8ASEpJ1pIRO1T4b2kL7pPqnU5Ce4fMZmMsh0xCy2gz/AktX7MqPQWDGe7VIcIfSrKmji0OsXbSziIx6grcugz5yYbfw1B5aa9iM+0KGg0Sh8Fap16ZXaM1r6YifqrhRqV3teEGMcdmiKq4fo4KwWe8fvmxMil4DO/VFzqbH9cVVG4pikcyMhVTslt9pClTLq2g2iRzeIksdrn/V6Ol47HIC+EemX/ld9XYC2yFfLky3sFiIlS0OmLNXI4nhWckcHDZ+EvaQJ4DYQnmXx/BfQ6eC+UPh/oSpwW2jiLZBER9WoTcKosUp3am71+9ErCt07MBmGW+XFlgkRKjzcRGd0=
  edge:
    source: mattk42/dpl
    branch: deis-v2-exit-status
  on:
    repo: BriefyHQ/briefy.leica
    branch: develop
